"""initial migration

Revision ID: 3444aa140b0b
Revises: 81e3e786e647
Create Date: 2017-03-23 14:17:15.401580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3444aa140b0b'
down_revision = '81e3e786e647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('auther_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'users', ['auther_id'], ['id'])
    op.drop_column('article', 'auther')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('auther', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'users', ['auther'], ['id'])
    op.drop_column('article', 'auther_id')
    # ### end Alembic commands ###
